#ifndef __COLDSENSES_CONF_
#define __COLDSENSES_CONF_

// #define COLDSENSES_MQTT_SERVER_URL ("192.168.1.2")
// #define COLDSENSES_MQTT_SERVER_PORT (9109)

#define COLDSENSES_GATEWAY_VERSION (2)
#define COLDSENSES_GATEWAY_VERSION_FULL ("0.2.0")

#ifndef COLDSENSES_DEBUG_BLE
#define COLDSENSES_DEBUG_BLE (0)
#endif

#ifndef COLDSENSES_DEBUG_WIFI
#define COLDSENSES_DEBUG_WIFI (0)
#endif

#ifndef COLDSENSES_DEBUG_EEPROM
#define COLDSENSES_DEBUG_EEPROM (1)
#endif

#ifndef COLDSENSES_DEBUG_TICK
#define COLDSENSES_DEBUG_TICK (0)
#endif

#ifndef COLDSENSES_DEBUG_MQTT
#define COLDSENSES_DEBUG_MQTT (1)
#endif

#ifndef MAX_TAGS_REMEMBER
#define MAX_TAGS_REMEMBER (16)
#endif

#ifndef MAX_NOTIFY_REMEMBER
#define MAX_NOTIFY_REMEMBER (64)
#endif

#ifndef TAG_ONLINE_TIEMOUT
#define TAG_ONLINE_TIEMOUT (60000)
#endif

#ifndef COLDSENSES_ALLOW_EEPROM
#define COLDSENSES_ALLOW_EEPROM (1)
#endif

#define SSID_MAXLENGTH (32)
#define WIFIPW_MAXLENGTH (64)

#ifndef COLDSENSES_MQTT_SERVER_URL
#define COLDSENSES_MQTT_SERVER_URL ("coldsenses.com")
#endif

#ifndef COLDSENSES_MQTT_SERVER_PORT
#define COLDSENSES_MQTT_SERVER_PORT (9100)
#endif

#define EEPROM_HEADER_KEY (0b0010110001000001010010010100011101001110110100110100101101010100L)

#define EEPROM_HEADER_ADDR (0)
#define EEPROM_VERSION_ADDR (EEPROM_HEADER_ADDR + sizeof(uint64_t))
#define EEPROM_SSID_ADDR (EEPROM_VERSION_ADDR + sizeof(uint16_t))
#define EEPROM_WIFIPW_ADDR (EEPROM_SSID_ADDR + SSID_MAXLENGTH + 1)
#define EEPROM_GPSLAT_ADDR (EEPROM_WIFIPW_ADDR + WIFIPW_MAXLENGTH + 1)
#define EEPROM_GPSLONG_ADDR (EEPROM_GPSLAT_ADDR + sizeof(double))
#define EEPROM_BUZZER_ENABLE_ADDR (EEPROM_GPSLONG_ADDR + sizeof(double))
#define EEPROM_TOTAL_BYTES (EEPROM_BUZZER_ENABLE_ADDR + sizeof(bool))
#endif